import type { Customer, Product, DeliveryCompany, Order } from "./types"

export const customers: Customer[] = [
  {
    id: "c1",
    name: "أحمد محمد",
    phone: "0501234567",
    address: "شارع الملك فهد، حي العليا",
    city: "الرياض",
    totalOrders: 15,
    returnCount: 1,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "c2",
    name: "فاطمة علي",
    phone: "0559876543",
    address: "شارع التحلية، حي السلامة",
    city: "جدة",
    totalOrders: 8,
    returnCount: 0,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "c3",
    name: "محمد العمري",
    phone: "0543216789",
    address: "شارع الأمير سلطان",
    city: "الدمام",
    totalOrders: 22,
    returnCount: 4,
    notes: "عميل يرفض الاستلام أحياناً",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "c4",
    name: "نورة السعيد",
    phone: "0567891234",
    address: "حي النسيم",
    city: "الرياض",
    totalOrders: 5,
    returnCount: 0,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "c5",
    name: "خالد الحربي",
    phone: "0512345678",
    address: "شارع الثلاثين",
    city: "بريدة",
    totalOrders: 12,
    returnCount: 2,
    createdAt: new Date("2024-02-01"),
  },
]

export const products: Product[] = [
  {
    id: "p1",
    name: "عباية سوداء فاخرة",
    price: 350,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "p2",
    name: "فستان سهرة",
    price: 450,
    isActive: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "p3",
    name: "حقيبة يد جلدية",
    price: 180,
    isActive: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "p4",
    name: "شال كشميري",
    price: 120,
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "p5",
    name: "أحذية نسائية",
    price: 220,
    isActive: false,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "p6",
    name: "طقم مجوهرات",
    price: 580,
    isActive: true,
    createdAt: new Date("2024-03-01"),
  },
]

export const deliveryCompanies: DeliveryCompany[] = [
  {
    id: "d1",
    name: "سمسا إكسبريس",
    phone: "920009999",
    cost: 25,
    isActive: true,
  },
  {
    id: "d2",
    name: "أرامكس",
    phone: "920027447",
    cost: 30,
    isActive: true,
  },
  {
    id: "d3",
    name: "ناقل",
    phone: "8002464444",
    cost: 22,
    isActive: true,
  },
  {
    id: "d4",
    name: "زاجل",
    phone: "920000177",
    cost: 28,
    isActive: false,
  },
]

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-001",
    customer: customers[0],
    items: [
      { productId: "p1", productName: "عباية سوداء فاخرة", quantity: 1, price: 350 },
      { productId: "p3", productName: "حقيبة يد جلدية", quantity: 1, price: 180 },
    ],
    status: "new",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[0],
    deliveryCost: 25,
    subtotal: 530,
    total: 555,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "o2",
    orderNumber: "ORD-002",
    customer: customers[1],
    items: [
      { productId: "p2", productName: "فستان سهرة", quantity: 1, price: 450 },
    ],
    status: "processing",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    paymentProof: "/proof.jpg",
    deliveryCompany: deliveryCompanies[1],
    deliveryCost: 30,
    subtotal: 450,
    total: 480,
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(),
  },
  {
    id: "o3",
    orderNumber: "ORD-003",
    customer: customers[2],
    items: [
      { productId: "p4", productName: "شال كشميري", quantity: 2, price: 120 },
      { productId: "p6", productName: "طقم مجوهرات", quantity: 1, price: 580 },
    ],
    status: "with_delivery",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[2],
    deliveryCost: 22,
    subtotal: 820,
    total: 842,
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(),
  },
  {
    id: "o4",
    orderNumber: "ORD-004",
    customer: customers[3],
    items: [
      { productId: "p1", productName: "عباية سوداء فاخرة", quantity: 2, price: 350 },
    ],
    status: "delivered",
    paymentMethod: "cod",
    paymentStatus: "paid",
    deliveryCompany: deliveryCompanies[0],
    deliveryCost: 25,
    subtotal: 700,
    total: 725,
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(),
  },
  {
    id: "o5",
    orderNumber: "ORD-005",
    customer: customers[4],
    items: [
      { productId: "p3", productName: "حقيبة يد جلدية", quantity: 1, price: 180 },
    ],
    status: "returned",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[1],
    deliveryCost: 30,
    subtotal: 180,
    total: 210,
    notes: "العميل رفض الاستلام",
    createdAt: new Date(Date.now() - 345600000),
    updatedAt: new Date(),
  },
  {
    id: "o6",
    orderNumber: "ORD-006",
    customer: customers[0],
    items: [
      { productId: "p6", productName: "طقم مجوهرات", quantity: 1, price: 580 },
    ],
    status: "delivered",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    deliveryCompany: deliveryCompanies[2],
    deliveryCost: 22,
    subtotal: 580,
    total: 602,
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(),
  },
]
