import type { Customer, Product, DeliveryCompany, Order } from "./types"

export const customers: Customer[] = [
  {
    id: "c1",
    name: "أحمد محمد",
    phone: "0501234567",
    address: "شارع الملك فهد، حي العليا",
    city: "الرياض",
    totalOrders: 15,
    returnCount: 1,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "c2",
    name: "فاطمة علي",
    phone: "0559876543",
    address: "شارع التحلية، حي السلامة",
    city: "جدة",
    totalOrders: 8,
    returnCount: 0,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "c3",
    name: "محمد العمري",
    phone: "0543216789",
    address: "شارع الأمير سلطان",
    city: "الدمام",
    totalOrders: 22,
    returnCount: 4,
    notes: "عميل يرفض الاستلام أحياناً",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "c4",
    name: "نورة السعيد",
    phone: "0567891234",
    address: "حي النسيم",
    city: "الرياض",
    totalOrders: 5,
    returnCount: 0,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "c5",
    name: "خالد الحربي",
    phone: "0512345678",
    address: "شارع الثلاثين",
    city: "بريدة",
    totalOrders: 12,
    returnCount: 2,
    createdAt: new Date("2024-02-01"),
  },
]

export const products: Product[] = [
  {
    id: "p1",
    name: "عباية سوداء فاخرة",
    type: "simple",
    price: 350,
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "p2",
    name: "فستان سهرة",
    type: "simple",
    price: 450,
    isActive: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "p3",
    name: "حقيبة يد جلدية",
    type: "simple",
    price: 180,
    isActive: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "p4",
    name: "شال كشميري",
    type: "simple",
    price: 120,
    isActive: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "p5",
    name: "أحذية نسائية",
    type: "simple",
    price: 220,
    isActive: false,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "p6",
    name: "طقم مجوهرات",
    type: "simple",
    price: 580,
    isActive: true,
    createdAt: new Date("2024-03-01"),
  },
  // Variant product example - T-Shirt with sizes and colors
  {
    id: "p7",
    name: "تي شيرت قطني",
    type: "variant",
    price: 80, // Base price
    isActive: true,
    variants: [
      { id: "v1", size: "S", color: "أبيض", price: 80, isActive: true },
      { id: "v2", size: "M", color: "أبيض", price: 80, isActive: true },
      { id: "v3", size: "L", color: "أبيض", price: 80, isActive: true },
      { id: "v4", size: "XL", color: "أبيض", price: 85, isActive: true },
      { id: "v5", size: "S", color: "أسود", price: 80, isActive: true },
      { id: "v6", size: "M", color: "أسود", price: 80, isActive: true },
      { id: "v7", size: "L", color: "أسود", price: 80, isActive: true },
      { id: "v8", size: "XL", color: "أسود", price: 85, isActive: true },
      { id: "v9", size: "S", color: "أزرق", price: 80, isActive: true },
      { id: "v10", size: "M", color: "أزرق", price: 80, isActive: true },
      { id: "v11", size: "L", color: "أزرق", price: 80, isActive: false }, // Disabled variant
      { id: "v12", size: "XL", color: "أزرق", price: 85, isActive: true },
    ],
    createdAt: new Date("2024-03-05"),
  },
  // Another variant product - Dress with sizes
  {
    id: "p8",
    name: "فستان كاجوال",
    type: "variant",
    price: 250,
    isActive: true,
    variants: [
      { id: "v13", size: "S", color: "بيج", price: 250, sku: "DRESS-BG-S", isActive: true },
      { id: "v14", size: "M", color: "بيج", price: 250, sku: "DRESS-BG-M", isActive: true },
      { id: "v15", size: "L", color: "بيج", price: 260, sku: "DRESS-BG-L", isActive: true },
      { id: "v16", size: "S", color: "وردي", price: 250, sku: "DRESS-PK-S", isActive: true },
      { id: "v17", size: "M", color: "وردي", price: 250, sku: "DRESS-PK-M", isActive: true },
      { id: "v18", size: "L", color: "وردي", price: 260, sku: "DRESS-PK-L", isActive: true },
    ],
    createdAt: new Date("2024-03-10"),
  },
]

export const deliveryCompanies: DeliveryCompany[] = [
  {
    id: "d1",
    name: "سمسا إكسبريس",
    phone: "920009999",
    cost: 25,
    isActive: true,
  },
  {
    id: "d2",
    name: "أرامكس",
    phone: "920027447",
    cost: 30,
    isActive: true,
  },
  {
    id: "d3",
    name: "ناقل",
    phone: "8002464444",
    cost: 22,
    isActive: true,
  },
  {
    id: "d4",
    name: "زاجل",
    phone: "920000177",
    cost: 28,
    isActive: false,
  },
]

export const orders: Order[] = [
  {
    id: "o1",
    orderNumber: "ORD-001",
    customer: customers[0],
    items: [
      { productId: "p1", productName: "عباية سوداء فاخرة", quantity: 1, price: 350 },
      { productId: "p3", productName: "حقيبة يد جلدية", quantity: 1, price: 180 },
    ],
    status: "new",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[0],
    deliveryCost: 25,
    subtotal: 530,
    total: 555,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "o2",
    orderNumber: "ORD-002",
    customer: customers[1],
    items: [
      { productId: "p2", productName: "فستان سهرة", quantity: 1, price: 450 },
    ],
    status: "processing",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    paymentProof: "/proof.jpg",
    deliveryCompany: deliveryCompanies[1],
    deliveryCost: 30,
    subtotal: 450,
    total: 480,
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(),
  },
  {
    id: "o3",
    orderNumber: "ORD-003",
    customer: customers[2],
    items: [
      { productId: "p4", productName: "شال كشميري", quantity: 2, price: 120 },
      { productId: "p6", productName: "طقم مجوهرات", quantity: 1, price: 580 },
    ],
    status: "with_delivery",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[2],
    deliveryCost: 22,
    subtotal: 820,
    total: 842,
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(),
  },
  {
    id: "o4",
    orderNumber: "ORD-004",
    customer: customers[3],
    items: [
      { productId: "p1", productName: "عباية سوداء فاخرة", quantity: 2, price: 350 },
    ],
    status: "delivered",
    paymentMethod: "cod",
    paymentStatus: "paid",
    deliveryCompany: deliveryCompanies[0],
    deliveryCost: 25,
    subtotal: 700,
    total: 725,
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(),
  },
  {
    id: "o5",
    orderNumber: "ORD-005",
    customer: customers[4],
    items: [
      { productId: "p3", productName: "حقيبة يد جلدية", quantity: 1, price: 180 },
    ],
    status: "returned",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[1],
    deliveryCost: 30,
    subtotal: 180,
    total: 210,
    notes: "العميل رفض الاستلام",
    createdAt: new Date(Date.now() - 345600000),
    updatedAt: new Date(),
  },
  {
    id: "o6",
    orderNumber: "ORD-006",
    customer: customers[0],
    items: [
      { productId: "p6", productName: "طقم مجوهرات", quantity: 1, price: 580 },
    ],
    status: "delivered",
    paymentMethod: "bank_transfer",
    paymentStatus: "paid",
    deliveryCompany: deliveryCompanies[2],
    deliveryCost: 22,
    subtotal: 580,
    total: 602,
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(),
  },
  // Order with variant product
  {
    id: "o7",
    orderNumber: "ORD-007",
    customer: customers[1],
    items: [
      { 
        productId: "p7", 
        productName: "تي شيرت قطني", 
        variantId: "v6",
        variantDetails: "Size: M, Color: أسود",
        quantity: 2, 
        price: 80 
      },
      { 
        productId: "p8", 
        productName: "فستان كاجوال", 
        variantId: "v14",
        variantDetails: "Size: M, Color: بيج",
        quantity: 1, 
        price: 250 
      },
    ],
    status: "new",
    paymentMethod: "cod",
    paymentStatus: "unpaid",
    deliveryCompany: deliveryCompanies[0],
    deliveryCost: 25,
    subtotal: 410,
    total: 435,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
